// Generated canonical MathML equations for RotorCalculator nomenclature
export const KEY_EQUATIONS_MATHML: Record<string, string> = {
  "R": "<mrow><msub><mi>A</mi><mi>DISK</mi></msub><mo>=</mo><mi>\u03c0</mi><msup><mi>R</mi><mn>2</mn></msup><mo>,</mo><mspace width=\"1em\"/><mi>\u03a9</mi><mi>R</mi><mo>=</mo><mfrac><mrow><mn>2</mn><mi>\u03c0</mi><mo>\u00b7</mo><mi mathvariant=\"normal\">rpm</mi><mo>\u00b7</mo><mi>R</mi></mrow><mn>60</mn></mfrac></mrow>",
  "Nb": "<mrow><msub><mi>\u03c3</mi><mi>REF</mi></msub><mo>=</mo><mfrac><mrow><msub><mi>N</mi><mi>b</mi></msub><mo>(</mo><msub><mi>c</mi><mi>R</mi></msub><mo>+</mo><msub><mi>c</mi><mi>T</mi></msub><mo>)</mo></mrow><mrow><mn>2</mn><mi>\u03c0</mi><mi>R</mi></mrow></mfrac></mrow>",
  "x0": "<mrow><msub><mi>x</mi><mn>0</mn></msub><mo>=</mo><mfrac><msub><mi>r</mi><mi>root</mi></msub><mi>R</mi></mfrac></mrow>",
  "c0": "<mrow><mi>c</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><msub><mi>c</mi><mi>R</mi></msub><mo>+</mo><mo>(</mo><msub><mi>c</mi><mi>T</mi></msub><mo>\u2212</mo><msub><mi>c</mi><mi>R</mi></msub><mo>)</mo><mi>x</mi></mrow>",
  "c1": "<mrow><mi>c</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><msub><mi>c</mi><mi>R</mi></msub><mo>+</mo><mo>(</mo><msub><mi>c</mi><mi>T</mi></msub><mo>\u2212</mo><msub><mi>c</mi><mi>R</mi></msub><mo>)</mo><mi>x</mi></mrow>",
  "taper": "<mrow><mi>taper</mi><mo>=</mo><mfrac><msub><mi>c</mi><mi>T</mi></msub><msub><mi>c</mi><mi>R</mi></msub></mfrac></mrow>",
  "sigmaRef": "<mrow><msub><mi>\u03c3</mi><mi>REF</mi></msub><mo>=</mo><mfrac><mrow><msub><mi>N</mi><mi>b</mi></msub><mspace width=\"0.12em\"/><msub><mi>A</mi><mi>REF</mi></msub></mrow><msub><mi>A</mi><mi>DISK</mi></msub></mfrac></mrow>",
  "sigmaAct": "<mrow><msub><mi>\u03c3</mi><mi>act</mi></msub><mo>=</mo><mfrac><mrow><msub><mi>N</mi><mi>b</mi></msub><mspace width=\"0.12em\"/><msub><mi>A</mi><mi>act</mi></msub></mrow><msub><mi>A</mi><mi>DISK</mi></msub></mfrac></mrow>",
  "sigmaT": "<mrow><msub><mi>\u03c3</mi><mi>TR</mi></msub><mo>=</mo><mn>3</mn><msubsup><mo>\u222b</mo><msub><mi>x</mi><mn>0</mn></msub><mn>1</mn></msubsup><mi>\u03c3</mi><mo>(</mo><mi>x</mi><mo>)</mo><msup><mi>x</mi><mn>2</mn></msup><mi>d</mi><mi>x</mi></mrow>",
  "AR": "<mrow><mi>AR</mi><mo>=</mo><mfrac><msup><mi>R</mi><mn>2</mn></msup><msub><mi>A</mi><mi>REF</mi></msub></mfrac><mo>=</mo><mfrac><mrow><mn>2</mn><mi>R</mi></mrow><mrow><msub><mi>c</mi><mi>R</mi></msub><mo>+</mo><msub><mi>c</mi><mi>T</mi></msub></mrow></mfrac></mrow>",
  "A": "<mrow><msub><mi>A</mi><mi>DISK</mi></msub><mo>=</mo><mi>\u03c0</mi><msup><mi>R</mi><mn>2</mn></msup></mrow>",
  "Ab": "<mrow><msub><mi>A</mi><mi>REF</mi></msub><mo>=</mo><mfrac><mrow><mi>R</mi><mo>(</mo><msub><mi>c</mi><mi>R</mi></msub><mo>+</mo><msub><mi>c</mi><mi>T</mi></msub><mo>)</mo></mrow><mn>2</mn></mfrac></mrow>",
  "Aact": "<mrow><msub><mi>A</mi><mi>act</mi></msub><mo>=</mo><msubsup><mo>\u222b</mo><mrow><msub><mi>x</mi><mn>0</mn></msub><mi>R</mi></mrow><mi>R</mi></msubsup><mi>c</mi><mspace width=\"0.12em\"/><mi>d</mi><mi>r</mi></mrow>",
  "thRoot": "<mrow><mi>\u03b8</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><msub><mi>\u03b8</mi><mi>R</mi></msub><mo>+</mo><msub><mi>\u03b8</mi><mi>twist</mi></msub><mfrac><mrow><mi>x</mi><mo>\u2212</mo><msub><mi>x</mi><mn>0</mn></msub></mrow><mrow><mn>1</mn><mo>\u2212</mo><msub><mi>x</mi><mn>0</mn></msub></mrow></mfrac><mo>+</mo><mi>\u0394</mi><mi>\u03b8</mi></mrow>",
  "thTip": "<mrow><msub><mi>\u03b8</mi><mi>twist</mi></msub><mo>=</mo><msub><mi>\u03b8</mi><mi>T</mi></msub><mo>\u2212</mo><msub><mi>\u03b8</mi><mi>R</mi></msub></mrow>",
  "thTwist": "<mrow><msub><mi>\u03b8</mi><mi>twist</mi></msub><mo>=</mo><msub><mi>\u03b8</mi><mi>T</mi></msub><mo>\u2212</mo><msub><mi>\u03b8</mi><mi>R</mi></msub></mrow>",
  "th75": "<mrow><msub><mi>\u03b8</mi><mn>75</mn></msub><mo>=</mo><msub><mi>\u03b8</mi><mi>R</mi></msub><mo>+</mo><mn>0.75</mn><mspace width=\"0.12em\"/><msub><mi>\u03b8</mi><mi>twist</mi></msub></mrow>",
  "airfoil": "<mrow><msub><mi>C</mi><mi>l</mi></msub><mo>=</mo><msub><mi>a</mi><mn>0</mn></msub><msub><mi>\u03b1</mi><mi>e</mi></msub><mo>,</mo><mspace width=\"1em\"/><msub><mi>C</mi><mi>d</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>d</mi><mn>0</mn></mrow></msub></mrow>",
  "a0": "<mrow><msub><mi>C</mi><mi>l</mi></msub><mo>=</mo><msub><mi>a</mi><mn>0</mn></msub><msub><mi>\u03b1</mi><mi>e</mi></msub></mrow>",
  "Cd0": "<mrow><msub><mi>C</mi><mi>d</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>d</mi><mn>0</mn></mrow></msub></mrow>",
  "tipModel": "<mrow><mtext>lift integrated from </mtext><msub><mi>x</mi><mn>0</mn></msub><mtext> to </mtext><mi>B</mi></mrow>",
  "B": "<mrow><mi>B</mi><mo>=</mo><mn>1</mn><mo>\u2212</mo><mfrac><msqrt><mrow><mn>2</mn><msub><mi>C</mi><mi>T</mi></msub></mrow></msqrt><msub><mi>N</mi><mi>b</mi></msub></mfrac></mrow>",
  "comp": "<mrow><mi>a</mi><mo>=</mo><mfrac><msub><mi>a</mi><mn>0</mn></msub><msqrt><mrow><mn>1</mn><mo>\u2212</mo><msup><mi>M</mi><mn>2</mn></msup></mrow></msqrt></mfrac></mrow>",
  "rpmNom": "<mrow><mi>\u03a9</mi><mo>=</mo><mfrac><mrow><mn>2</mn><mi>\u03c0</mi><mo>\u00b7</mo><mi mathvariant=\"normal\">rpm</mi></mrow><mn>60</mn></mfrac></mrow>",
  "h": "<mrow><mi>p</mi><mo>=</mo><mn>101325</mn><mspace width=\"0.12em\"/><msup><mrow><mo>(</mo><mrow><mn>1</mn><mo>\u2212</mo><mfrac><mrow><mn>0.0065</mn><mspace width=\"0.12em\"/><mi>h</mi></mrow><mn>288.15</mn></mfrac></mrow><mo>)</mo></mrow><mn>5.2561</mn></msup><mspace width=\"0.28em\"/><mi mathvariant=\"normal\">Pa</mi></mrow>",
  "T0": "<mrow><mi>\u03c1</mi><mo>=</mo><mfrac><mi>p</mi><mrow><msub><mi>R</mi><mi>gas</mi></msub><mi>T</mi></mrow></mfrac><mo>,</mo><mspace width=\"1em\"/><mi>a</mi><mo>=</mo><msqrt><mrow><mi>\u03b3</mi><msub><mi>R</mi><mi>gas</mi></msub><mi>T</mi></mrow></msqrt></mrow>",
  "mu": "<mrow><msub><mi>\u03bc</mi><mi>x</mi></msub><mo>=</mo><mfrac><msub><mi>V</mi><mi>x</mi></msub><mrow><mi>\u03a9</mi><mi>R</mi></mrow></mfrac></mrow>",
  "Vx": "<mrow><msub><mi>V</mi><mi>x</mi></msub><mo>=</mo><msub><mi>\u03bc</mi><mi>x</mi></msub><mi>\u03a9</mi><mi>R</mi></mrow>",
  "alpha": "<mrow><msub><mi>\u03bc</mi><mi>z</mi></msub><mo>=</mo><mo>\u2212</mo><msub><mi>\u03bc</mi><mi>x</mi></msub><mi>tan</mi><mi>\u03b1</mi></mrow>",
  "Vz": "<mrow><msub><mi>V</mi><mi>z</mi></msub><mo>=</mo><msub><mi>\u03bc</mi><mi>z</mi></msub><mi>\u03a9</mi><mi>R</mi></mrow>",
  "muz": "<mrow><msub><mi>\u03bc</mi><mi>z</mi></msub><mo>=</mo><mfrac><msub><mi>V</mi><mi>z</mi></msub><mrow><mi>\u03a9</mi><mi>R</mi></mrow></mfrac><mo>=</mo><mo>\u2212</mo><msub><mi>\u03bc</mi><mi>x</mi></msub><mi>tan</mi><mi>\u03b1</mi></mrow>",
  "trim": "<mrow><mi>T</mi><mo>=</mo><msub><mi>C</mi><mi>T</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "rpm": "<mrow><mi>\u03a9</mi><mi>R</mi><mo>=</mo><mfrac><mrow><mn>2</mn><mi>\u03c0</mi><mo>\u00b7</mo><mi mathvariant=\"normal\">rpm</mi><mo>\u00b7</mo><mi>R</mi></mrow><mn>60</mn></mfrac></mrow>",
  "coll": "<mrow><mi>\u03b8</mi><mo>(</mo><mi>x</mi><mo>)</mo><mo>=</mo><msub><mi>\u03b8</mi><mi>R</mi></msub><mo>+</mo><msub><mi>\u03b8</mi><mi>twist</mi></msub><mfrac><mrow><mi>x</mi><mo>\u2212</mo><msub><mi>x</mi><mn>0</mn></msub></mrow><mrow><mn>1</mn><mo>\u2212</mo><msub><mi>x</mi><mn>0</mn></msub></mrow></mfrac><mo>+</mo><mi>\u0394</mi><mi>\u03b8</mi></mrow>",
  "Ttgt": "<mrow><mi>T</mi><mo>=</mo><msub><mi>C</mi><mi>T</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "CTtgt": "<mrow><msub><mi>C</mi><mi>T</mi></msub><mo>=</mo><mfrac><mi>T</mi><mrow><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow></mfrac></mrow>",
  "inflow": "<mrow><msub><mi>\u03bb</mi><mi>d</mi></msub><mo>(</mo><mi>x</mi><mo>,</mo><mi>\u03c8</mi><mo>)</mo><mo>=</mo><mi>\u03bb</mi><mo>+</mo><msub><mi>\u03bb</mi><mi>i</mi></msub><mi>x</mi><mo>(</mo><msub><mi>K</mi><mi>x</mi></msub><mi>cos</mi><mi>\u03c8</mi><mo>+</mo><msub><mi>K</mi><mi>y</mi></msub><mi>sin</mi><mi>\u03c8</mi><mo>)</mo></mrow>",
  "kind": "<mrow><msub><mi>C</mi><mrow><mi>Q</mi><mi>i</mi></mrow></msub><mo>=</mo><msub><mi>k</mi><mi>ind</mi></msub><msub><mi>\u03bb</mi><mi>i</mi></msub><msub><mi>C</mi><mi>T</mi></msub><mo>+</mo><msub><mi>\u03bc</mi><mi>z</mi></msub><msub><mi>C</mi><mi>T</mi></msub><mo>\u2212</mo><mi>\u03bc</mi><msub><mi>C</mi><mrow><mi>H</mi><mi>i</mi></mrow></msub></mrow>",
  "drag": "<mrow><mi>d</mi><mi>D</mi><mo>=</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>\u03c1</mi><msup><mi>W</mi><mn>2</mn></msup><mi>c</mi><mspace width=\"0.12em\"/><msub><mi>C</mi><mrow><mi>d</mi><mn>0</mn></mrow></msub><mspace width=\"0.12em\"/><mi>d</mi><mi>r</mi></mrow>",
  "T": "<mrow><mi>T</mi><mo>=</mo><msub><mi>C</mi><mi>T</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "P": "<mrow><mi>P</mi><mo>=</mo><mi>Q</mi><mi>\u03a9</mi><mo>=</mo><msub><mi>C</mi><mi>Q</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>3</mn></msup></mrow>",
  "Pi": "<mrow><msub><mi>P</mi><mi>i</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>Q</mi><mi>i</mi></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>3</mn></msup></mrow>",
  "P0": "<mrow><msub><mi>P</mi><mn>0</mn></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>Q</mi><mn>0</mn></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>3</mn></msup></mrow>",
  "Q": "<mrow><mi>Q</mi><mo>=</mo><msub><mi>C</mi><mi>Q</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup><mi>R</mi></mrow>",
  "H": "<mrow><mi>H</mi><mo>=</mo><msub><mi>C</mi><mi>H</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "Y": "<mrow><mi>Y</mi><mo>=</mo><msub><mi>C</mi><mi>Y</mi></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "Mx": "<mrow><msub><mi>M</mi><mi>x</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>M</mi><mi>x</mi></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup><mi>R</mi></mrow>",
  "My": "<mrow><msub><mi>M</mi><mi>y</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>M</mi><mi>y</mi></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup><mi>R</mi></mrow>",
  "DL": "<mrow><mi>DL</mi><mo>=</mo><mfrac><mi>T</mi><msub><mi>A</mi><mi>DISK</mi></msub></mfrac></mrow>",
  "PL": "<mrow><mi>PL</mi><mo>=</mo><mfrac><mi>T</mi><mi>P</mi></mfrac></mrow>",
  "Vztot": "<mrow><msub><mi>V</mi><mrow><mi>z</mi><mo>,</mo><mi>tot</mi></mrow></msub><mo>=</mo><msub><mi>V</mi><mi>z</mi></msub><mo>+</mo><msub><mi>v</mi><mi>i</mi></msub><mo>=</mo><mi>\u03bb</mi><mi>\u03a9</mi><mi>R</mi></mrow>",
  "Vadv": "<mrow><msub><mi>V</mi><mi>adv</mi></msub><mo>=</mo><mi>\u03a9</mi><mi>R</mi><mo>+</mo><msub><mi>V</mi><mi>x</mi></msub></mrow>",
  "Vret": "<mrow><msub><mi>V</mi><mi>ret</mi></msub><mo>=</mo><mi>\u03a9</mi><mi>R</mi><mo>\u2212</mo><msub><mi>V</mi><mi>x</mi></msub></mrow>",
  "Mret": "<mrow><msub><mi>M</mi><mi>ret</mi></msub><mo>=</mo><mfrac><mrow><mo stretchy=\"false\">|</mo><mi>\u03a9</mi><mi>R</mi><mo>\u2212</mo><msub><mi>V</mi><mi>x</mi></msub><mo stretchy=\"false\">|</mo></mrow><mi>a</mi></mfrac></mrow>",
  "aoaAdv25": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>0.25</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "aoaRet25": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>0.25</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "phiAdv25": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "phiRet25": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "aoaAdv50": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>0.50</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "aoaRet50": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>0.50</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "phiAdv50": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "phiRet50": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "aoaAdv75": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>0.75</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "aoaRet75": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>0.75</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "phiAdv75": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "phiRet75": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "aoaAdvTip": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>1.0</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "aoaRetTip": "<mrow><msub><mi>\u03b1</mi><mi>s</mi></msub><mo>=</mo><mi>\u03b8</mi><mo>(</mo><mn>1.0</mn><mo>)</mo><mo>\u2212</mo><mi>\u03c6</mi></mrow>",
  "phiAdvTip": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "phiRetTip": "<mrow><mi>\u03c6</mi><mo>=</mo><mi>atan2</mi><mo>(</mo><msub><mi>u</mi><mi>P</mi></msub><mo>,</mo><msub><mi>u</mi><mi>T</mi></msub><mo>)</mo></mrow>",
  "vi": "<mrow><msub><mi>v</mi><mi>i</mi></msub><mo>=</mo><msub><mi>\u03bb</mi><mi>i</mi></msub><mi>\u03a9</mi><mi>R</mi></mrow>",
  "CT": "<mrow><msub><mi>C</mi><mi>T</mi></msub><mo>=</mo><mfrac><mi>T</mi><mrow><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow></mfrac></mrow>",
  "CQ": "<mrow><msub><mi>C</mi><mi>Q</mi></msub><mo>=</mo><mfrac><mi>Q</mi><mrow><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup><mi>R</mi></mrow></mfrac><mo>=</mo><msub><mi>C</mi><mrow><mi>Q</mi><mi>i</mi></mrow></msub><mo>+</mo><msub><mi>C</mi><mrow><mi>Q</mi><mn>0</mn></mrow></msub><mo>=</mo><msub><mi>C</mi><mi>P</mi></msub></mrow>",
  "CQi": "<mrow><msub><mi>C</mi><mrow><mi>Q</mi><mi>i</mi></mrow></msub><mo>=</mo><msub><mi>k</mi><mi>ind</mi></msub><msub><mi>\u03bb</mi><mi>i</mi></msub><msub><mi>C</mi><mi>T</mi></msub><mo>+</mo><msub><mi>\u03bc</mi><mi>z</mi></msub><msub><mi>C</mi><mi>T</mi></msub><mo>\u2212</mo><mi>\u03bc</mi><msub><mi>C</mi><mrow><mi>H</mi><mi>i</mi></mrow></msub></mrow>",
  "Qi": "<mrow><msub><mi>Q</mi><mi>i</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>Q</mi><mi>i</mi></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup><mi>R</mi></mrow>",
  "Q0": "<mrow><msub><mi>Q</mi><mn>0</mn></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>Q</mi><mn>0</mn></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup><mi>R</mi></mrow>",
  "Hi": "<mrow><msub><mi>H</mi><mi>i</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>H</mi><mi>i</mi></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "H0": "<mrow><msub><mi>H</mi><mn>0</mn></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>H</mi><mn>0</mn></mrow></msub><mspace width=\"0.12em\"/><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>2</mn></msup></mrow>",
  "Pair": "<mrow><msub><mi>P</mi><mi>air</mi></msub><mo>=</mo><msub><mi>C</mi><mi>Pair</mi></msub><mi>\u03c1</mi><msub><mi>A</mi><mi>DISK</mi></msub><msup><mrow><mo>(</mo><mi>\u03a9</mi><mi>R</mi><mo>)</mo></mrow><mn>3</mn></msup><mo>=</mo><mi>P</mi><mo>+</mo><mi>\u03bc</mi><mi>H</mi><mi>\u03a9</mi><mi>R</mi></mrow>",
  "CQ0": "<mrow><msub><mi>C</mi><mrow><mi>Q</mi><mn>0</mn></mrow></msub><mo>=</mo><msubsup><mo>\u222b</mo><msub><mi>x</mi><mn>0</mn></msub><mn>1</mn></msubsup><mfrac><mrow><mi>\u03c3</mi><mo>(</mo><mi>x</mi><mo>)</mo><msub><mi>C</mi><mrow><mi>d</mi><mn>0</mn></mrow></msub></mrow><mn>2</mn></mfrac><msub><mrow><mo>\u27e8</mo><mi>W</mi><msub><mi>u</mi><mi>T</mi></msub><mi>x</mi><mo>\u27e9</mo></mrow><mi>\u03c8</mi></msub><mi>d</mi><mi>x</mi></mrow>",
  "CH": "<mrow><msub><mi>C</mi><mi>H</mi></msub><mo>=</mo><msub><mi>C</mi><mrow><mi>H</mi><mi>i</mi></mrow></msub><mo>+</mo><msub><mi>C</mi><mrow><mi>H</mi><mn>0</mn></mrow></msub></mrow>",
  "CHi": "<mrow><msub><mi>C</mi><mrow><mi>H</mi><mi>i</mi></mrow></msub><mo>=</mo><mfrac><mi>a</mi><mn>4</mn></mfrac><mo>[</mo><mi>\u03bb</mi><mi>\u03bc</mi><msub><mi>\u0398</mi><mn>0</mn></msub><mo>+</mo><msub><mi>\u03bb</mi><mrow><mn>1</mn><mi>s</mi></mrow></msub><mo>(</mo><msub><mi>\u0398</mi><mn>2</mn></msub><mo>\u2212</mo><mn>2</mn><mi>\u03bb</mi><msub><mi>I</mi><mn>1</mn></msub><mo>)</mo><mo>]</mo></mrow>",
  "CH0": "<mrow><msub><mi>C</mi><mrow><mi>H</mi><mn>0</mn></mrow></msub><mo>=</mo><msubsup><mo>\u222b</mo><msub><mi>x</mi><mn>0</mn></msub><mn>1</mn></msubsup><mfrac><mrow><mi>\u03c3</mi><mo>(</mo><mi>x</mi><mo>)</mo><msub><mi>C</mi><mrow><mi>d</mi><mn>0</mn></mrow></msub></mrow><mn>2</mn></mfrac><msub><mrow><mo>\u27e8</mo><mi>W</mi><mo>(</mo><mi>x</mi><mi>sin</mi><mi>\u03c8</mi><mo>+</mo><mi>\u03bc</mi><mo>)</mo><mo>\u27e9</mo></mrow><mi>\u03c8</mi></msub><mi>d</mi><mi>x</mi></mrow>",
  "CY": "<mrow><msub><mi>C</mi><mi>Y</mi></msub><mo>=</mo><mo>\u2212</mo><mfrac><mi>a</mi><mn>4</mn></mfrac><msub><mi>\u03bb</mi><mrow><mn>1</mn><mi>c</mi></mrow></msub><mo>(</mo><msub><mi>\u0398</mi><mn>2</mn></msub><mo>\u2212</mo><mn>2</mn><mi>\u03bb</mi><msub><mi>I</mi><mn>1</mn></msub><mo>)</mo></mrow>",
  "CMx": "<mrow><msub><mi>C</mi><mrow><mi>M</mi><mi>x</mi></mrow></msub><mo>=</mo><mo>\u2212</mo><mfrac><mrow><mi>a</mi><mi>\u03bc</mi></mrow><mn>2</mn></mfrac><mo>(</mo><msub><mi>\u0398</mi><mn>2</mn></msub><mo>\u2212</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>\u03bb</mi><msub><mi>I</mi><mn>1</mn></msub><mo>)</mo><mo>+</mo><mfrac><mi>a</mi><mn>4</mn></mfrac><msub><mi>\u03bb</mi><mrow><mn>1</mn><mi>s</mi></mrow></msub><msub><mi>I</mi><mn>3</mn></msub></mrow>",
  "CMy": "<mrow><msub><mi>C</mi><mrow><mi>M</mi><mi>y</mi></mrow></msub><mo>=</mo><mfrac><mi>a</mi><mn>4</mn></mfrac><msub><mi>\u03bb</mi><mrow><mn>1</mn><mi>c</mi></mrow></msub><msub><mi>I</mi><mn>3</mn></msub></mrow>",
  "CPair": "<mrow><msub><mi>C</mi><mi>Pair</mi></msub><mo>=</mo><msub><mi>k</mi><mi>ind</mi></msub><msub><mi>\u03bb</mi><mi>i</mi></msub><msub><mi>C</mi><mi>T</mi></msub><mo>+</mo><msub><mi>\u03bc</mi><mi>z</mi></msub><msub><mi>C</mi><mi>T</mi></msub><mo>+</mo><msub><mi>C</mi><mrow><mi>Q</mi><mn>0</mn></mrow></msub><mo>+</mo><mi>\u03bc</mi><msub><mi>C</mi><mrow><mi>H</mi><mn>0</mn></mrow></msub></mrow>",
  "CTs": "<mrow><mfrac><msub><mi>C</mi><mi>T</mi></msub><msub><mi>\u03c3</mi><mi>TR</mi></msub></mfrac></mrow>",
  "CLbar": "<mrow><msub><mover accent=\"true\"><mi>C</mi><mo>\u00af</mo></mover><mi>L</mi></msub><mo>=</mo><mfrac><mrow><mn>6</mn><msub><mi>C</mi><mi>T</mi></msub></mrow><msub><mi>\u03c3</mi><mi>TR</mi></msub></mfrac></mrow>",
  "FM": "<mrow><mi>FoM</mi><mo>=</mo><mfrac><mrow><msubsup><mi>C</mi><mi>T</mi><mrow><mn>3</mn><mo>/</mo><mn>2</mn></mrow></msubsup><mo>/</mo><msqrt><mn>2</mn></msqrt></mrow><mrow><msub><mi>k</mi><mi>ind</mi></msub><msubsup><mi>C</mi><mi>T</mi><mrow><mn>3</mn><mo>/</mo><mn>2</mn></mrow></msubsup><mo>/</mo><msqrt><mn>2</mn></msqrt><mo>+</mo><msub><mi>C</mi><mrow><mi>Q</mi><mn>0</mn></mrow></msub></mrow></mfrac></mrow>",
  "LDe": "<mrow><msub><mrow><mo>(</mo><mi>L</mi><mo>/</mo><mi>D</mi><mo>)</mo></mrow><mi>e</mi></msub><mo>=</mo><mfrac><mrow><mi>\u03bc</mi><msub><mi>C</mi><mi>T</mi></msub></mrow><msub><mi>C</mi><mi>Pair</mi></msub></mfrac></mrow>",
  "lam": "<mrow><mi>\u03bb</mi><mo>=</mo><msub><mi>\u03bc</mi><mi>z</mi></msub><mo>+</mo><msub><mi>\u03bb</mi><mi>i</mi></msub></mrow>",
  "lami": "<mrow><msub><mi>C</mi><mi>T</mi></msub><mo>=</mo><mn>2</mn><msup><mi>B</mi><mn>2</mn></msup><msub><mi>\u03bb</mi><mi>i</mi></msub><msqrt><mrow><msup><mi>\u03bc</mi><mn>2</mn></msup><mo>+</mo><msup><mi>\u03bb</mi><mn>2</mn></msup></mrow></msqrt></mrow>",
  "lamh": "<mrow><msub><mi>\u03bb</mi><mi>h</mi></msub><mo>=</mo><msqrt><mfrac><msub><mi>C</mi><mi>T</mi></msub><mn>2</mn></mfrac></msqrt></mrow>",
  "muLam": "<mrow><mfrac><mi>\u03bc</mi><mi>\u03bb</mi></mfrac><mo>=</mo><mfrac><msub><mi>\u03bc</mi><mi>x</mi></msub><mrow><msub><mi>\u03bc</mi><mi>z</mi></msub><mo>+</mo><msub><mi>\u03bb</mi><mi>i</mi></msub></mrow></mfrac></mrow>",
  "Tc": "<mrow><msub><mi>T</mi><mi>c</mi></msub><mo>=</mo><mfrac><mi>T</mi><mrow><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>\u03c1</mi><msup><mi>V</mi><mn>2</mn></msup><msub><mi>A</mi><mi>DISK</mi></msub></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>2</mn><msub><mi>C</mi><mi>T</mi></msub></mrow><msubsup><mi>\u03bc</mi><mo>\u221e</mo><mn>2</mn></msubsup></mfrac></mrow>",
  "Pc": "<mrow><msub><mi>P</mi><mi>c</mi></msub><mo>=</mo><mfrac><mi>P</mi><mrow><mfrac><mn>1</mn><mn>2</mn></mfrac><mi>\u03c1</mi><msup><mi>V</mi><mn>3</mn></msup><msub><mi>A</mi><mi>DISK</mi></msub></mrow></mfrac><mo>=</mo><mfrac><mrow><mn>2</mn><msub><mi>C</mi><mi>P</mi></msub></mrow><msubsup><mi>\u03bc</mi><mo>\u221e</mo><mn>3</mn></msubsup></mfrac></mrow>",
  "Kx": "<mrow><msub><mi>K</mi><mi>x</mi></msub><mo>=</mo><mi>tan</mi><mfrac><mi>\u03c7</mi><mn>2</mn></mfrac></mrow>",
  "Ky": "<mrow><msub><mi>K</mi><mi>y</mi></msub><mo>=</mo><mo>\u2212</mo><mn>2</mn><mi>\u03bc</mi></mrow>",
  "chi": "<mrow><mi>tan</mi><mfrac><mi>\u03c7</mi><mn>2</mn></mfrac><mo>=</mo><mfrac><mi>\u03bc</mi><mrow><msqrt><mrow><msup><mi>\u03bc</mi><mn>2</mn></msup><mo>+</mo><msup><mi>\u03bb</mi><mn>2</mn></msup></mrow></msqrt><mo>+</mo><mo stretchy=\"false\">|</mo><mi>\u03bb</mi><mo stretchy=\"false\">|</mo></mrow></mfrac></mrow>",
  "Bres": "<mrow><mi>B</mi><mo>=</mo><mn>1</mn><mo>\u2212</mo><mfrac><msqrt><mrow><mn>2</mn><msub><mi>C</mi><mi>T</mi></msub></mrow></msqrt><msub><mi>N</mi><mi>b</mi></msub></mfrac></mrow>",
  "OmR": "<mrow><mi>\u03a9</mi><mi>R</mi><mo>=</mo><mfrac><mrow><mn>2</mn><mi>\u03c0</mi><mo>\u00b7</mo><mi mathvariant=\"normal\">rpm</mi><mo>\u00b7</mo><mi>R</mi></mrow><mn>60</mn></mfrac></mrow>",
  "Mtip": "<mrow><msub><mi>M</mi><mi>tip</mi></msub><mo>=</mo><mfrac><mrow><mi>\u03a9</mi><mi>R</mi></mrow><mi>a</mi></mfrac></mrow>",
  "Madv": "<mrow><msub><mi>M</mi><mi>adv</mi></msub><mo>=</mo><mfrac><mrow><mi>\u03a9</mi><mi>R</mi><mo>(</mo><mn>1</mn><mo>+</mo><msub><mi>\u03bc</mi><mi>x</mi></msub><mo>)</mo></mrow><mi>a</mi></mfrac></mrow>",
  "rho": "<mrow><mi>\u03c1</mi><mo>=</mo><mfrac><mi>p</mi><mrow><msub><mi>R</mi><mi>gas</mi></msub><mi>T</mi></mrow></mfrac></mrow>",
  "p": "<mrow><mi>p</mi><mo>=</mo><mn>101325</mn><mspace width=\"0.12em\"/><msup><mrow><mo>(</mo><mrow><mn>1</mn><mo>\u2212</mo><mfrac><mrow><mn>0.0065</mn><mspace width=\"0.12em\"/><mi>h</mi></mrow><mn>288.15</mn></mfrac></mrow><mo>)</mo></mrow><mn>5.2561</mn></msup><mspace width=\"0.28em\"/><mi mathvariant=\"normal\">Pa</mi></mrow>",
  "a": "<mrow><mi>a</mi><mo>=</mo><msqrt><mrow><mi>\u03b3</mi><msub><mi>R</mi><mi>gas</mi></msub><mi>T</mi></mrow></msqrt></mrow>",
  "tip_none": "<mrow><mi>B</mi><mo>=</mo><mn>1</mn></mrow>",
  "tip_fixed": "<mrow><mi>B</mi><mo>=</mo><msub><mi>B</mi><mi>fixed</mi></msub></mrow>",
  "tip_sissingh": "<mrow><mi>B</mi><mo>=</mo><mn>1</mn><mo>\u2212</mo><mfrac><msqrt><mrow><mn>2</mn><msub><mi>C</mi><mi>T</mi></msub></mrow></msqrt><msub><mi>N</mi><mi>b</mi></msub></mfrac></mrow>",
  "comp_off": "<mrow><mi>a</mi><mo>=</mo><msub><mi>a</mi><mn>0</mn></msub></mrow>",
  "comp_pg": "<mrow><mi>a</mi><mo>=</mo><mfrac><msub><mi>a</mi><mn>0</mn></msub><msqrt><mrow><mn>1</mn><mo>\u2212</mo><msubsup><mi>M</mi><mi>eff</mi><mn>2</mn></msubsup></mrow></msqrt></mfrac></mrow>"
};

/**
 * Renders a nomenclature equation into formatted MathML with native typography.
 */
export function renderEquationMathML(key: string, rawEq?: string): string {
  if (key && KEY_EQUATIONS_MATHML[key]) {
    return `<math display="block">${KEY_EQUATIONS_MATHML[key]}</math>`;
  }
  if (!rawEq || !rawEq.trim()) return "";
  
  // Clean fallback formatter for any unmapped mathematical equation
  const escaped = rawEq
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return `<math display="block"><mrow><mtext>${escaped}</mtext></mrow></math>`;
}
